### PR TITLE
Juno: Move DHCP agent updates onto their own thread, coalesce port updates.

### PR DESCRIPTION
**Pull request by fasaxc**

### CODE REVIEW

**Comment by fasaxc** [comment]
Moved some code around to make it much clearer which methods belong to which thread, simplified the loop and fixed up the UTs.

**Comment by fasaxc** [comment]
One thing this loses is we we don't wait to return to the RPC call but I'm not clear what would happen if we did wait.  I think there's only one RPC thread that we care about so if we block it then we'll just end up  processing everything sequential like we did before.

**Comment by nelljerram** [comment]
Hi @fasaxc - I've pushed an alternative implementation of this idea in https://github.com/Metaswitch/calico-neutron/pull/10.  It implements the decoupling inside call_driver, with a separate thread per-network, and I think that makes the change simpler and more clearly contained.

I've tested it by hand - not yet in a real long-running churn test, but with creating and deleting 10 instances at once - and it appears to work, with "Consumed!" logs indicating that the intended optimization is really happening.

One odd thing - that I don't understand, and that might be related to your customer's original observing of old IP addresses not being cleaned up from the Dnsmasq config file.  When I deleted 10 instances at once, the log indicated that port_delete_end was being called, but nothing else happened, and so the Dnsmasq config was left unchanged.  That suggests

```
        port = self.cache.get_port_by_id(payload['port_id'])
```

returning None, so I added a "No port" log for that case, and indeed began seeing that log.  Then I added another log inside get_port_by_id, to explore that further - and then port_delete_end processing started working normally, and I no longer saw the "No port" log.  I currently can't explain it - but a hint of some strange intermittent thing that can prevent port_delete_end processing from running properly.  Also I would guess unrelated to the change that I've made here.

Please can you take a look at let me know what you think?  If you like it, I guess the next steps would be
- putting it through a better churn test of our own
- offering it for testing to our customers, to check it works for them too
- me submitting it upstream to Neutron.

**Comment by matthewdupre** [comment]
We're going to merge these fixes now because we need them for customers.  It's fine to change these into something more upstream friendly (for example your fix in progress @neiljerram).

**Pull request merged**
