### PR TITLE
Icehouse: Move DHCP driver updates onto worker thread.  

### PR DESCRIPTION
**Pull request by fasaxc**
Coalesce port updates for performance.

### CODE REVIEW

**Comment by matthewdupre** [comment]
@fasaxc this fails the UTs.  The PPA builds require them to work, so I'm going to have to back this out.

Log is at https://launchpadlibrarian.net/208592275/buildlog_ubuntu-trusty-i386.neutron_1%3A2014.1.4-0ubuntu2calico0.23_BUILDING.txt.gz

Highlights:

```
======================================================================
FAIL: neutron.tests.unit.test_dhcp_agent.TestDhcpAgent.test_resync_if_needed
neutron.tests.unit.test_dhcp_agent.TestDhcpAgent.test_resync_if_needed
----------------------------------------------------------------------
_StringException: Empty attachments:
  pythonlogging:''
  pythonlogging:'neutron.api.extensions'
  stderr
  stdout

Traceback (most recent call last):
  File "/«PKGBUILDDIR»/neutron/tests/unit/test_dhcp_agent.py", line 334, in test_resync_if_needed
    dhcp._resync_if_needed()
  File "/usr/lib/python2.7/dist-packages/testtools/testcase.py", line 876, in __exit__
    raise AssertionError(error_msg)
AssertionError: ExpectedError not raised.


======================================================================
```

**Comment by matthewdupre** [comment]
Actually I'm don't see a lot of point backing this out, given we don't build directly from this branch anyway.  Please just follow up with another PR to fix the UTs up.

Thanks.

**Comment by nelljerram** [comment]
```
                                                                                  Ah, those wonderful white box UTs...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Matt DupreSent: Monday, 8 June 2015 18:30To: Metaswitch/calico-neutronReply To: Metaswitch/calico-neutronCc: Neil JerramSubject: Re: [calico-neutron] Icehouse: Move DHCP driver updates onto worker thread.   (#6)@fasaxc this fails the UTs.  The PPA builds require them to work, so I'm going to have to back this out.
```

Log is at https://launchpadlibrarian.net/208592275/buildlog_ubuntu-trusty-i386.neutron_1%3A2014.1.4-0ubuntu2calico0.23_BUILDING.txt.gz

Highlights:

FAIL: neutron.tests.unit.test_dhcp_agent.TestDhcpAgent.test_resync_if_needed

neutron.tests.unit.test_dhcp_agent.TestDhcpAgent.test_resync_if_needed

_StringException: Empty attachments:
  pythonlogging:''
  pythonlogging:'neutron.api.extensions'
  stderr
  stdout

Traceback (most recent call last):
  File "/«PKGBUILDDIR»/neutron/tests/unit/test_dhcp_agent.py", line 334, in test_resync_if_needed
    dhcp.resync_if_needed()
  File "/usr/lib/python2.7/dist-packages/testtools/testcase.py", line 876, in __exit_
    raise AssertionError(error_msg)
AssertionError: ExpectedError not raised.

—Reply to this email directly or view it on GitHub.

**Comment by fasaxc** [comment]
Thought I'd fixed those up.  Can confirm though; repros here with `./run_tests.sh neutron.tests.unit.test_dhcp_agent.TestDhcpAgent`

**Comment by fasaxc** [comment]
@matthewdupre  @neiljerram  I put up a PR to fix the UT breakage: #13.  It was a bad backport from the 2.2 version of the fix.

**Pull request merged**
